In [1]:
#Basic Operations in Array
import numpy as np
a=np.array([1,2,3])
b=np.array([1,4,9])

In [2]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 2  6 12]
[ 0 -2 -6]
[ 1  8 27]
[ 1.          0.5         0.33333333]
[    1    16 19683]


In [3]:
#Universsal functions in numpy
print(np.sin(a))
print(np.log(a))
print(np.exp(a))
print(np.dot(a,b))
print(np.sqrt(a))
print(a<5)

[ 0.84147098  0.90929743  0.14112001]
[ 0.          0.69314718  1.09861229]
[  2.71828183   7.3890561   20.08553692]
36
[ 1.          1.41421356  1.73205081]
[ True  True  True]


In [4]:
#Summing along axes
b=np.arange(16).reshape((4,4))
print(b)
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 28 32 36]
[ 6 22 38 54]
[0 1 2 3]


In [5]:
#Indexing and Slicing
print(b)
print("SLicing and Indexing")
print(b[1:3,-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
SLicing and Indexing
[ 7 11]


In [6]:
#Shape Manipulation
a=np.arange(25)

In [7]:
print(a)
print(a.reshape(5,5))
print(a.reshape(5,5).T)
print(a.reshape(5,5).ravel())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Stacking together different array

In [8]:
a=np.arange(4).reshape(2,2)
b=np.array([1,4,9,16]).reshape(2,2)
print(a,b)

[[0 1]
 [2 3]] [[ 1  4]
 [ 9 16]]


In [9]:
print(np.vstack((a,b)))
print(np.hstack((a,b)))
#Numpy has some weird function like row_stack and column_stack
#The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

#Using column vector
 from numpy import newaxis
a=np.array([1,10])
a[:,newaxis]

[[ 0  1]
 [ 2  3]
 [ 1  4]
 [ 9 16]]
[[ 0  1  1  4]
 [ 2  3  9 16]]


NameError: name 'newaxis' is not defined

In [ ]:
#automatic reshaping
a=np.arange(36)
a.shape=6,6
print(a)

## Splitting a bigger array into smaller one

In [ ]:
np.vsplit(a,2)

In [ ]:
#Linear algebra
#x+y=3
#3x-y=1
a=np.array([1,1])
b=np.array([3,-1])
c=np.vstack((a,b))
y=np.array((3,1)).T

In [ ]:
np.linalg.solve(c, y)

In [ ]:
np.linalg.eig(c)