## Fancy Indexing

In [1]:
#importing the numpy library
import numpy as np

In [2]:
a=np.empty((10,5))

In [6]:
for x in range(10):
    a[x]=x
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.]]


In [8]:
b=a>4

In [9]:
a[b]

array([ 5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,
        7.,  7.,  8.,  8.,  8.,  8.,  8.,  9.,  9.,  9.,  9.,  9.])