In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
#Importing Libraries for meta learning Algorithm called Adaboost
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn import datasets

In [5]:
#Loading Iris Dataset
iris=datasets.load_iris()

#Loading our AdaBoostClassifier Model
clf=AdaBoostClassifier()

In [6]:
#Fitting our Model on data
clf.fit(iris.data[:-5],iris.target[:-5])

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [7]:
#Predicting on test data
clf.predict(iris.data[-2])

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [8]:
#Label of test data
iris.target[-2]

2

In [9]:
scores = cross_val_score(clf, iris.data, iris.target)

In [10]:
print(scores)

[ 0.98039216  0.94117647  0.97916667]


In [19]:
#Implenting Linear Regression
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit([[1,1],[2,2],[3,3]],[1,2,3])
reg.predict([4,4])

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 4.])

In [20]:
#performance Matrix
print(reg.coef_)
print(reg.score)
print(reg.intercept_)

[ 0.5  0.5]
<bound method RegressorMixin.score of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)>
4.4408920985e-16
